### ISSUE TITLE
接口优于继承

### ISSUE THREAD

**Issue by SunnyMarkLiu** [QianguoSun/DirectorPattern-1-#1]
`package director;

public abstract class EncryptComponet {
	public abstract void encrypt();
}`

抽象类改为接口：

`package director;

public interface EncryptComponet {
	public void encrypt();
}`

**Comment by QianguoSun** [comment]
蒙大神指导，改下重新上传，感谢

**Comment by QianguoSun** [comment]
这个demo为抽象类的，下一个demo为接口的实现，方便以后自己的学习
